### ISSUE TITLE
Create a purge option that will delete the .qcd directory when uninstalling

### ISSUE THREAD

**Issue by lordadamson** [lordadamson/QuickCD#4]
in the `uninstall.sh` make it so that if a user passes the option `--purge` the script will delete the `~/.qcd` directory.

**Comment by modelorona** [comment]
Let me take a look at this. First time using Bash but I'm sure I can get it

**Comment by Furinkazan33** [comment]
Can I contribute ?

**Comment by lordadamson** [comment]
Hi @Furinkazan33 I'm afraid @modelorona has already done it.
If you have any other improvements or suggestions please let me know.
You can always take a look at the other issues and see if you can help with any of them.
Thank you :D
